"""Add game_user Association Table

Revision ID: d6d09bcb2824
Revises: e7464f33566c
Create Date: 2023-05-10 14:56:06.775836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d09bcb2824'
down_revision = 'e7464f33566c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
